# encoding: UTF-8

GATEWAY_BIN := $(BIN_DIR)/gateway

GATEWAY_INC_DIR := $(GATEWAY_DIR)/inc
GATEWAY_SRC_DIR := $(GATEWAY_DIR)/src
GATEWAY_OBJ_DIR := $(GATEWAY_DIR)/obj
GATEWAY_DEP_DIR := $(GATEWAY_DIR)/dep

# GATEWAY INCLUDES
GATEWAY_INCLUDES := -I $(GATEWAY_INC_DIR)
GATEWAY_INCLUDES += 

# GATEWAY DEFINITIONS
GATEWAY_DEFINITIONS := 
GATEWAY_DEFINITIONS += 

# GATEWAY SOURCES WITHOUT DIRECTORY PATHS
GATEWAY_SRCS_NOTDIR := $(notdir $(wildcard $(GATEWAY_SRC_DIR)/*.c))

# GATEWAY OBJECTS
GATEWAY_OBJS := $(patsubst %.c, $(GATEWAY_OBJ_DIR)/%.o, $(GATEWAY_SRCS_NOTDIR))

# GATEWAY DEPENDENCIES
GATEWAY_DEPS := $(patsubst %.c, $(GATEWAY_DEP_DIR)/%.d, $(GATEWAY_SRCS_NOTDIR))

$(GATEWAY_OBJ_DIR)/%.o: $(GATEWAY_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(GATEWAY_INCLUDES) -MMD -o $@
	@$(MV) $(patsubst %.o, %.d, $@) $(GATEWAY_DEP_DIR)

-include $(GATEWAY_DEPS)