# encoding: UTF-8

GATEWAY_BIN := $(BIN_DIR)/GATEWAY

GATEWAY_INC_DIR := $(GATEWAY_DIR)/inc
GATEWAY_SRC_DIR := $(GATEWAY_DIR)/src
GATEWAY_OBJ_DIR := $(GATEWAY_DIR)/obj
GATEWAY_DEP_DIR := $(GATEWAY_DIR)/obj

# GATEWAY INCLUDES
GATEWAY_INCLUDES := -I $(GATEWAY_INC_DIR)
GATEWAY_INCLUDES += 

# GATEWAY DEFINITIONS
GATEWAY_DEFINITIONS := 
GATEWAY_DEFINITIONS += 

# GATEWAY SOURCES
GATEWAY_SRCS := $(wildcard $(GATEWAY_SRC_DIR)/*.c)
GATEWAY_SRCS_NOTDIR := $(notdir $(GATEWAY_SRCS))

# GATEWAY OBJECTS
GATEWAY_OBJS := $(patsubst %.c, $(GATEWAY_OBJ_DIR)/%.o, $(GATEWAY_SRCS_NOTDIR))
GATEWAY_OBJS_NOTDIR := $(notdir $(GATEWAY_OBJS))

# GATEWAY DEPENDENCIES
GATEWAY_DEPS := $(patsubst %.o, $(GATEWAY_DEP_DIR)/%.d, $(GATEWAY_OBJS_NOTDIR))
GATEWAY_DEPS_NOTDIR := $(notdir $(GATEWAY_DEPS))

$(GATEWAY_OBJ_DIR)/%.o: $(GATEWAY_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(GATEWAY_INCLUDES) -MMD -o $@

-include $(GATEWAY_DEPS)