# encoding: UTF-8

VCLIENT_BIN := $(BIN_DIR)/vclient

VCLIENT_INC_DIR := $(VCLIENT_DIR)/inc
VCLIENT_SRC_DIR := $(VCLIENT_DIR)/src
VCLIENT_OBJ_DIR := $(VCLIENT_DIR)/obj
VCLIENT_DEP_DIR := $(VCLIENT_DIR)/obj

# VCLIENT INCLUDES
VCLIENT_INCLUDES := -I $(VCLIENT_INC_DIR)
VCLIENT_INCLUDES += 

# VCLIENT DEFINITIONS
VCLIENT_DEFINITIONS := 
VCLIENT_DEFINITIONS += 

# VCLIENT SOURCES
VCLIENT_SRCS := $(wildcard $(VCLIENT_SRC_DIR)/*.c)
VCLIENT_SRCS_NOTDIR := $(notdir $(VCLIENT_SRCS))

# VCLIENT OBJECTS
VCLIENT_OBJS := $(patsubst %.c, $(VCLIENT_OBJ_DIR)/%.o, $(VCLIENT_SRCS_NOTDIR))
VCLIENT_OBJS_NOTDIR := $(notdir $(VCLIENT_OBJS))

# VCLIENT DEPENDENCIES
VCLIENT_DEPS := $(patsubst %.o, $(VCLIENT_DEP_DIR)/%.d, $(VCLIENT_OBJS_NOTDIR))
VCLIENT_DEPS_NOTDIR := $(notdir $(VCLIENT_DEPS))

$(VCLIENT_OBJ_DIR)/%.o: $(VCLIENT_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(VCLIENT_INCLUDES) -MMD -o $@

-include $(VCLIENT_DEPS)