# encoding: UTF-8

MCLIENT_BIN := $(BIN_DIR)/MCLIENT

MCLIENT_INC_DIR := $(MCLIENT_DIR)/inc
MCLIENT_SRC_DIR := $(MCLIENT_DIR)/src
MCLIENT_OBJ_DIR := $(MCLIENT_DIR)/obj
MCLIENT_DEP_DIR := $(MCLIENT_DIR)/obj

# MCLIENT INCLUDES
MCLIENT_INCLUDES := -I $(MCLIENT_INC_DIR)
MCLIENT_INCLUDES += 

# MCLIENT DEFINITIONS
MCLIENT_DEFINITIONS := 
MCLIENT_DEFINITIONS += 

# MCLIENT SOURCES
MCLIENT_SRCS := $(wildcard $(MCLIENT_SRC_DIR)/*.c)
MCLIENT_SRCS_NOTDIR := $(notdir $(MCLIENT_SRCS))

# MCLIENT OBJECTS
MCLIENT_OBJS := $(patsubst %.c, $(MCLIENT_OBJ_DIR)/%.o, $(MCLIENT_SRCS_NOTDIR))
MCLIENT_OBJS_NOTDIR := $(notdir $(MCLIENT_OBJS))

# MCLIENT DEPENDENCIES
MCLIENT_DEPS := $(patsubst %.o, $(MCLIENT_DEP_DIR)/%.d, $(MCLIENT_OBJS_NOTDIR))
MCLIENT_DEPS_NOTDIR := $(notdir $(MCLIENT_DEPS))

$(MCLIENT_OBJ_DIR)/%.o: $(MCLIENT_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(MCLIENT_INCLUDES) -MMD -o $@

-include $(MCLIENT_DEPS)