# encoding: UTF-8

DESTSTATION_BIN := $(BIN_DIR)/deststation

DESTSTATION_INC_DIR := $(DESTSTATION_DIR)/inc
DESTSTATION_SRC_DIR := $(DESTSTATION_DIR)/src
DESTSTATION_OBJ_DIR := $(DESTSTATION_DIR)/.obj
DESTSTATION_DEP_DIR := $(DESTSTATION_DIR)/.dep

# DESTSTATION INCLUDES
DESTSTATION_INCLUDES := -I $(DESTSTATION_INC_DIR)
DESTSTATION_INCLUDES += 

# DESTSTATION DEFINITIONS
DESTSTATION_DEFINITIONS :=
DESTSTATION_DEFINITIONS += 

# DESTSTATION SOURCES WITHOUT DIRECTORIES
DESTSTATION_SRCS_NOTDIR := $(notdir $(wildcard $(DESTSTATION_SRC_DIR)/*.c))

# DESTSTATION OBJECTS
DESTSTATION_OBJS := $(patsubst %.c, $(DESTSTATION_OBJ_DIR)/%.o, $(DESTSTATION_SRCS_NOTDIR))

# DESTSTATION DEPENDENCIES
DESTSTATION_DEPS := $(patsubst %.c, $(DESTSTATION_DEP_DIR)/%.d, $(DESTSTATION_SRCS_NOTDIR))

$(DESTSTATION_OBJ_DIR)/%.o: $(DESTSTATION_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(DESTSTATION_INCLUDES) -MMD -MF $(DESTSTATION_DEP_DIR)/$(notdir $(patsubst %.o, %.d, $@)) -o $@

-include $(DESTSTATION_DEPS)