# encoding: UTF-8

DESTSTATION_BIN := $(BIN_DIR)/DESTSTATION

DESTSTATION_INC_DIR := $(DESTSTATION_DIR)/inc
DESTSTATION_SRC_DIR := $(DESTSTATION_DIR)/src
DESTSTATION_OBJ_DIR := $(DESTSTATION_DIR)/obj
DESTSTATION_DEP_DIR := $(DESTSTATION_DIR)/obj

# DESTSTATION INCLUDES
DESTSTATION_INCLUDES := -I $(DESTSTATION_INC_DIR)
DESTSTATION_INCLUDES += 

# DESTSTATION DEFINITIONS
DESTSTATION_DEFINITIONS :=
DESTSTATION_DEFINITIONS += 

# DESTSTATION SOURCES
DESTSTATION_SRCS := $(wildcard $(DESTSTATION_SRC_DIR)/*.c)
DESTSTATION_SRCS_NOTDIR := $(notdir $(DESTSTATION_SRCS))

# DESTSTATION OBJECTS
DESTSTATION_OBJS := $(patsubst %.c, $(DESTSTATION_OBJ_DIR)/%.o, $(DESTSTATION_SRCS_NOTDIR))
DESTSTATION_OBJS_NOTDIR := $(notdir $(DESTSTATION_OBJS))

# DESTSTATION DEPENDENCIES
DESTSTATION_DEPS := $(patsubst %.o, $(DESTSTATION_DEP_DIR)/%.d, $(DESTSTATION_OBJS_NOTDIR))
DESTSTATION_DEPS_NOTDIR := $(notdir $(DESTSTATION_DEPS))

$(DESTSTATION_OBJ_DIR)/%.o: $(DESTSTATION_SRC_DIR)/%.c
	$(CC) -c $< $(FLAGS) $(DESTSTATION_INCLUDES) -MMD -o $@

-include $(DESTSTATION_DEPS)